### ISSUE TITLE
Review current PWA state

### ISSUE THREAD

**Issue by uveta** [ips-ag/demo-progressive-web-app#13]
As  a designer, I need to review current state of PWA and point out any UI/UX issues and potential improvements

**Comment by SternUxi** [comment]
First adjustments UX/UI for app usability, layout and styling

1. Allow conditional Login / Sign up button next to user icon (outlined rounded sm?)
2. Spacing for user avatar menu
3. Selection of Metrics can be integrated in home page (omit in bottom menu > see point nr.5)
4. Move notifications icon next to user profile icon
5. Reserve bottom menu in mobile for quick actions ( eg. Search, Start a call, People )
6. Solve ripple deformation in side menu or remove global style https://github.com/mui/material-ui/pull/10671 (resolved)
7. Side menu could have expanded state by default for desktop layout
8. Move top menu to sidebar (fig 4)
9. Position arrow for expand/collapse side menu at bottom
10. Set up Styling system with CSS VARS or BEM or similar to allow global styling
11. Bring up font-size for page title H3 to about 22px or equivalent in EM
12. Define H1 H2 H3 styles etc. in CSS VARS
13. Use REM only for UI elements and general text properties (page title, breadcrumbs, text, button text etc.) in EM
14. Active highlighting of selected menu links (underline)
15. refactor mobile menu to Full width panel with close option (fig 3)
16. Add breadcrumbs navigation (fig 1 ,2)
17. Populate home screen with CTA links, eg, Start a meeting, get location, .. ( Will provide UI design using Material )

_Fig1_
![image](https://user-images.githubusercontent.com/109517286/181749551-6f16cf30-3ee1-415e-825f-a9feb6ddf5c7.png)
_Fig2_
![Breadcrumb mobile](https://user-images.githubusercontent.com/109517286/181748492-81b94089-337f-4184-a753-2cc4b4e7e6a4.png)
_Fig3_
![Menu mobile](https://user-images.githubusercontent.com/109517286/181748685-b2ea7831-e361-4c62-a593-d904bf0ed512.png)
_Fig4_
![fig4](https://user-images.githubusercontent.com/109517286/181749705-9f754c16-c4c7-4598-b9b5-65cd27db972e.png)

**Comment by SternUxi** [comment]
Resolve in linked task #19
